export { default as IconAnnotation } from './IconAnnotation.vue';
export { default as IconClose } from './IconClose.vue';
export { default as IconConfig } from './IconConfig.vue';
export { default as IconEdit } from './IconEdit.vue';
export { default as IconEditPencil } from './IconEditPencil.vue'
export { default as IconHeartEmpty } from './IconHeartEmpty.vue';
export { default as IconHeartFull } from './IconHeartFull.vue';
export { default as IconMicrophoneEmpty } from './IconMicrophoneEmpty.vue';
export { default as IconMicrophoneFull } from './IconMicrophoneFull.vue';
export { default as IconPlay } from './IconPlay.vue';
export { default as IconProfileEdit } from './IconProfileEdit.vue';
export { default as IconSecurity } from './IconSecurity.vue';
export { default as IconSwatchbook } from './IconSwatchbook.vue';
export { default as IconTools } from './IconTools.vue';
export { default as IconTrash } from './IconTrash.vue';
export { default as IconUndo } from './IconUndo.vue';
